<a href="https://colab.research.google.com/github/Thchieu/ML_2023/blob/main/Lab_6_20130211_TranHaiChieu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This lab is to deal with classification task using **Random Forests** and **Naïve Bayes** algorithms with/without **Feature Selection**. 

*   **Deadline: 23:59, 25/03/2023**



# Import libraries

In [1]:
# code
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics._plot.confusion_matrix import ConfusionMatrixDisplay
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn import svm
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from prettytable import PrettyTable
from sklearn.ensemble import RandomForestClassifier

from sklearn.feature_selection import chi2
from sklearn.naive_bayes import GaussianNB
from sklearn.decomposition import PCA
from sklearn.feature_selection import RFE
from sklearn.ensemble import ExtraTreesClassifier

     

from sklearn.feature_selection import chi2
from sklearn.feature_selection import SelectKBest
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_selection import f_classif



#Task 1. 
Task 1. Compare the performance of selected classification algorithms including **Random forest**, **NaiveBayes**, and **SVM** with **mnist** dataset based on **accuracy, precision, recall, f1** measures according to **without using selection feature** and **using selection feature**.



In [2]:
# code
mnist = datasets.load_digits()
X = mnist['data']
y = mnist['target']

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

#Không dùng selecttion
# Radial Basis
clf = svm.SVC(kernel='rbf') 
clf.fit(X_train, y_train)
y_pred_rad = clf.predict(X_test)

accuracy_rad = accuracy_score(y_test, y_pred_rad)
precision_rad = precision_score(y_test, y_pred_rad, average='macro')
recall_rad = recall_score(y_test, y_pred_rad, average='macro')
f1_rad = f1_score(y_test, y_pred_rad, average='macro')

#Create a Random Forest Classifier
clf_rf=RandomForestClassifier(n_estimators=100)
#Train the model using the training sets
clf_rf.fit(X_train,y_train)
y_pred_rf = clf.predict(X_test)

accuracy_rf = accuracy_score(y_test, y_pred_rf)
precision_rf = precision_score(y_test, y_pred_rf, average='macro')
recall_rf = recall_score(y_test, y_pred_rf, average='macro')
f1_rf = f1_score(y_test, y_pred_rf, average='macro')

# Naive Bayes
model = GaussianNB()
model.fit(X_train, y_train)
y_pred_nb = model.predict(X_test)

accuracy_nb = accuracy_score(y_test, y_pred_nb)
precision_nb = precision_score(y_test, y_pred_nb, average='macro')
recall_nb = recall_score(y_test, y_pred_nb, average='macro')
f1_nb = f1_score(y_test, y_pred_nb, average='macro')

In [4]:
# ExtraTreesClassifier
model = ExtraTreesClassifier(n_estimators=10)
model.fit(X_train, y_train)

y_pred_ext = model.predict(X_test)

accuracy_ext = accuracy_score(y_test, y_pred_ext)
precision_ext = precision_score(y_test, y_pred_ext, average='macro')
recall_ext = recall_score(y_test, y_pred_ext, average='macro')
f1_ext = f1_score(y_test, y_pred_ext, average='macro')


In [5]:
mnist2 = datasets.load_digits()
x= mnist2['data']
y= mnist2['target']
x.shape  #in so mau du lieu, tong so thuoc tinh
X_new = SelectKBest(chi2, k=2).fit_transform(x,y)
X_new.shape #sau khi scale

X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size=0.3, random_state=0)

In [6]:
#dùng selecttion
# Radial Basis
clf = svm.SVC(kernel='rbf') 
clf.fit(X_train, y_train)
y_pred_rad1 = clf.predict(X_test)

accuracy_rad1 = accuracy_score(y_test, y_pred_rad1)
precision_rad1 = precision_score(y_test, y_pred_rad1, average='macro',zero_division=0)
recall_rad1 = recall_score(y_test, y_pred_rad1, average='macro')
f1_rad1 = f1_score(y_test, y_pred_rad1, average='macro')

#Create a Random Forest Classifier
clf_rf=RandomForestClassifier(n_estimators=100)
#Train the model using the training sets
clf_rf.fit(X_train,y_train)
y_pred_rf1 = clf.predict(X_test)

accuracy_rf1 = accuracy_score(y_test, y_pred_rf1)
precision_rf1 = precision_score(y_test, y_pred_rf1, average='macro')
recall_rf1 = recall_score(y_test, y_pred_rf1, average='macro')
f1_rf1 = f1_score(y_test, y_pred_rf1, average='macro')

# Naive Bayes
model = GaussianNB()
model.fit(X_train, y_train)
y_pred_nb1 = model.predict(X_test)

accuracy_nb1 = accuracy_score(y_test, y_pred_nb1)
precision_nb1 = precision_score(y_test, y_pred_nb1, average='macro',zero_division=0)
recall_nb1 = recall_score(y_test, y_pred_nb1, average='macro')
f1_nb1 = f1_score(y_test, y_pred_nb1, average='macro')
     

t= PrettyTable(['','acc','pre','recall','f1'])


t.add_row(['Radial Basis', round(accuracy_rad,2),round(precision_rad,2),round(recall_rad,2),round(f1_rad,2)])
t.add_row(['Random Forest', round(accuracy_rf,2),round(precision_rf,2),round(recall_rf,2),round(f1_rf,2)])
t.add_row(['Naive Bayes', round(accuracy_nb,2),round(precision_nb,2),round(recall_nb,2),round(f1_nb,2)])
# t.add_row(['SVM', round(accuracy_rad,2),round(precision_rad,2),round(recall_rad,2),round(f1_rad,2)])

t2= PrettyTable(['','acc','pre','recall','f1'])
t2.add_row(['Radial Basis', round(accuracy_rad1,2),round(precision_rad1,2),round(recall_rad1,2),round(f1_rad1,2)])
t2.add_row(['Random Forest', round(accuracy_rf1,2),round(precision_rf1,2),round(recall_rf1,2),round(f1_rf1,2)])
t2.add_row(['Naive Bayes', round(accuracy_nb1,2),round(precision_nb1,2),round(recall_nb1,2),round(f1_nb1,2)])
# t2.add_row(['ExtraTreesClassifier', round(accuracy_ext,2),round(precision_ext,2),round(recall_ext,2),round(f1_ext,2)])

print(t)
print(t2)

+---------------+------+------+--------+------+
|               | acc  | pre  | recall |  f1  |
+---------------+------+------+--------+------+
|  Radial Basis | 0.99 | 0.99 |  0.99  | 0.99 |
| Random Forest | 0.99 | 0.99 |  0.99  | 0.99 |
|  Naive Bayes  | 0.85 | 0.87 |  0.85  | 0.85 |
+---------------+------+------+--------+------+
+---------------+------+------+--------+------+
|               | acc  | pre  | recall |  f1  |
+---------------+------+------+--------+------+
|  Radial Basis | 0.39 | 0.38 |  0.38  | 0.35 |
| Random Forest | 0.39 | 0.38 |  0.38  | 0.35 |
|  Naive Bayes  | 0.33 | 0.32 |  0.34  | 0.29 |
+---------------+------+------+--------+------+


/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


#Task 2. 
For given bank dataset (bank.csv) having the following attributes :
1.	**age** (numeric)
2.	**job** : type of job (categorical: 'admin.','blue-collar','entrepreneur','housemaid','management','retired','self-employed','services','student','technician','unemployed','unknown')
3.	**marital** : marital status (categorical: 'divorced','married','single','unknown'; note: 'divorced' means divorced or widowed)
4.	**education** (categorical: 'basic.4y','basic.6y','basic.9y','high.school','illiterate','professional.course','university.degree','unknown')
5.	**default**: has credit in default? (categorical: 'no','yes','unknown')
6.	**housing**: has housing loan? (categorical: 'no','yes','unknown')
7.	**loan**: has personal loan? (categorical: 'no','yes','unknown')
8.	**contact**: contact communication type (categorical: 'cellular','telephone')
9.	**month**: last contact month of year (categorical: 'jan', 'feb', 'mar', ..., 'nov', 'dec')
10.	**day_of_week**: last contact day of the week (categorical: 'mon','tue','wed','thu','fri')
11.	**duration**: last contact duration, in seconds (numeric). Important note: this attribute highly affects the output target (e.g., if duration=0 then y='no'). Yet, the duration is not known before a call is performed. Also, after the end of the call y is obviously known. Thus, this input should only be included for benchmark purposes and should be discarded if the intention is to have a realistic predictive model.
12.	**campaign**: number of contacts performed during this campaign and for this client (numeric, includes last contact)
13.	**pdays**: number of days that passed by after the client was last contacted from a previous campaign (numeric; 999 means client was not previously contacted)
14.	**previous**: number of contacts performed before this campaign and for this client (numeric)
15.	**poutcome**: outcome of the previous marketing campaign (categorical: 'failure','nonexistent','success')
Output variable (desired target):
16.	**y**. has the client subscribed a term deposit? (binary: 'yes','no')



#3.1. Apply StandardScaler() function to columns that contains numerical data ('age', 'balance', 'day', 'campaign', 'pdays', 'previous')

In [7]:
#code
from google.colab import drive
drive.mount('/content/gdrive')
%cd '/content/gdrive/MyDrive/ML'

df = pd.read_csv("bank.csv")


Mounted at /content/gdrive
/content/gdrive/MyDrive/ML


In [8]:
from sklearn.preprocessing import StandardScaler

column = ['age', 'balance', 'day', 'campaign', 'pdays', 'previous']
object= StandardScaler()

scale = object.fit_transform(df[column]) 
print(scale)


[[ 1.49150488  0.25252514 -1.26574556 -0.55416834 -0.48118405 -0.36325984]
 [ 1.23967567 -0.4599736  -1.26574556 -0.55416834 -0.48118405 -0.36325984]
 [-0.0194704  -0.0801603  -1.26574556 -0.55416834 -0.48118405 -0.36325984]
 ...
 [-0.77495804 -0.46493443  0.39689074 -0.18678537 -0.48118405 -0.36325984]
 [ 0.14841574 -0.47392593 -0.90946635 -0.18678537  1.10957066  1.81833188]
 [-0.6070719  -0.47392593 -0.79070662 -0.55416834 -0.48118405 -0.36325984]]


#3.2. Apply Encode Categorical Value (OneHotEncoder) to transfrom categorical data to numerical data ('job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome')

In [9]:
#code
ohe = OneHotEncoder()
column = ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome']
transformed = ohe.fit_transform(df[column]).toarray()

ohe_df = pd.DataFrame(transformed, columns=ohe.get_feature_names_out(column))
df_ohe = pd.concat([df, ohe_df], axis=1)
df_ohe.drop(column, axis=1, inplace=True)
print(df_ohe.head())

   age  balance  day  duration  campaign  pdays  previous deposit  job_admin.  \
0   59     2343    5      1042         1     -1         0     yes         1.0   
1   56       45    5      1467         1     -1         0     yes         1.0   
2   41     1270    5      1389         1     -1         0     yes         0.0   
3   55     2476    5       579         1     -1         0     yes         0.0   
4   54      184    5       673         2     -1         0     yes         1.0   

   job_blue-collar  ...  month_jun  month_mar  month_may  month_nov  \
0              0.0  ...        0.0        0.0        1.0        0.0   
1              0.0  ...        0.0        0.0        1.0        0.0   
2              0.0  ...        0.0        0.0        1.0        0.0   
3              0.0  ...        0.0        0.0        1.0        0.0   
4              0.0  ...        0.0        0.0        1.0        0.0   

   month_oct  month_sep  poutcome_failure  poutcome_other  poutcome_success  \
0      

#3.3. Apply **Decision tree, Random forest, kNN, NaïveBayes** to preproceed dataset in the previous steps. Then compare the obtained results using **accuracy, precision, recall, f1** measures.

In [10]:
#code
X = df_ohe.drop('deposit', axis=1)
y = df_ohe['deposit']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
# Decision tree
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)

accuracy_dt = accuracy_score(y_test, y_pred_dt)
precision_dt = precision_score(y_test, y_pred_dt, average='macro')
recall_dt = recall_score(y_test, y_pred_dt, average='macro')
f1_dt = f1_score(y_test, y_pred_dt, average='macro')

#Random forest
clf=RandomForestClassifier(n_estimators=100)
clf.fit(X_train,y_train)
y_pred_Rf = clf.predict(X_test)

accuracy_rf = accuracy_score(y_test, y_pred_Rf)
precision_rf = precision_score(y_test, y_pred_Rf, average='macro')
recall_rf = recall_score(y_test, y_pred_Rf, average='macro')
f1_rf = f1_score(y_test, y_pred_Rf, average='macro')

# kNN
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred_knn = knn.predict(X_test)

accuracy_knn = accuracy_score(y_test, y_pred_knn)
precision_knn = precision_score(y_test, y_pred_knn, average='macro')
recall_knn = recall_score(y_test, y_pred_knn, average='macro')
f1_knn = f1_score(y_test, y_pred_knn, average='macro')

#NaiveBayes 
clf = GaussianNB()
clf.fit(X_train, y_train)
y_pred_Bayes = clf.predict(X_test)

accuracy_bayes = accuracy_score(y_test, y_pred_Bayes)
precision_bayes = precision_score(y_test, y_pred_Bayes, average='macro')
recall_bayes = recall_score(y_test, y_pred_Bayes, average='macro')
f1_bayes = f1_score(y_test, y_pred_Bayes, average='macro')

     

data={'accuracy':[accuracy_dt,accuracy_rf,accuracy_knn,accuracy_bayes],
      'precision':[precision_dt,precision_rf,precision_knn,precision_bayes],
      'recall':[recall_dt,recall_rf,recall_knn,recall_bayes],
      'f1':[f1_dt,f1_rf,f1_knn,f1_bayes]}

row_labels = ['Decision tree', 'Random forest','kNN', 'NaiveBayes']

dframe = pd.DataFrame(data=data,index = row_labels)
dframe

accuracy  precision    recall        f1
Decision tree  0.792475   0.791445  0.791470  0.791457
Random forest  0.853688   0.853360  0.855069  0.853450
kNN            0.737235   0.735933  0.735682  0.735798
NaiveBayes     0.734249   0.741226  0.726322  0.726910

#3.4. Using selection feature to above dataset, then compare the classification results with those in Task 2.3. 

In [11]:
#code
X = df_ohe.drop('deposit', axis=1)
y = df_ohe['deposit']
X_new = SelectKBest(score_func=f_classif, k=7).fit_transform(X,y)
X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size=0.3, random_state=0)

In [12]:
#dùng selecttion
# Radial Basis
clf = svm.SVC(kernel='rbf') 
clf.fit(X_train, y_train)
y_pred_rad1 = clf.predict(X_test)

accuracy_rad1 = accuracy_score(y_test, y_pred_rad1)
precision_rad1 = precision_score(y_test, y_pred_rad1, average='macro')
recall_rad1 = recall_score(y_test, y_pred_rad1, average='macro')
f1_rad1 = f1_score(y_test, y_pred_rad1, average='macro')

#Create a Random Forest Classifier
clf_rf=RandomForestClassifier(n_estimators=100)
#Train the model using the training sets
clf_rf.fit(X_train,y_train)
y_pred_rf1 = clf.predict(X_test)

accuracy_rf1 = accuracy_score(y_test, y_pred_rf1)
precision_rf1 = precision_score(y_test, y_pred_rf1, average='macro')
recall_rf1 = recall_score(y_test, y_pred_rf1, average='macro')
f1_rf1 = f1_score(y_test, y_pred_rf1, average='macro')

# Naive Bayes
model = GaussianNB()
model.fit(X_train, y_train)
y_pred_nb1 = model.predict(X_test)

accuracy_nb1 = accuracy_score(y_test, y_pred_nb1)
precision_nb1 = precision_score(y_test, y_pred_nb1, average='macro')
recall_nb1 = recall_score(y_test, y_pred_nb1, average='macro')
f1_nb1 = f1_score(y_test, y_pred_nb1, average='macro')

# kNN
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred_knn1 = knn.predict(X_test)

accuracy_knn1 = accuracy_score(y_test, y_pred_knn1)
precision_knn1 = precision_score(y_test, y_pred_knn1, average='macro')
recall_knn1 = recall_score(y_test, y_pred_knn1, average='macro')
f1_knn1 = f1_score(y_test, y_pred_knn1, average='macro')

     

data={'accuracy':[accuracy_rad1,accuracy_rf1,accuracy_knn1,accuracy_nb1],
      'precision':[precision_rad1,precision_rf1,precision_knn1,precision_nb1],
      'recall':[recall_rad1,recall_rf1,recall_knn1,recall_nb1],
      'f1':[f1_rad1,f1_rf,f1_knn1,f1_nb1]}

row_labels = ['Decision tree', 'Random forest','kNN', 'NaiveBayes']

dframe = pd.DataFrame(data=data,index = row_labels)
dframe

accuracy  precision    recall        f1
Decision tree  0.719319   0.718777  0.715361  0.716093
Random forest  0.719319   0.718777  0.715361  0.853450
kNN            0.751866   0.750869  0.751712  0.751115
NaiveBayes     0.745297   0.766634  0.733951  0.733169

#Task 4. 
For a given dataset in the Lab #5 (**credit card dataset**), perform feature selection and thencompare the performance of selected classification algorithms (Decision Tree, kNN, Logistic Regression, SVM, Random Forest and NaiveBayes) based on accuracy, precision, recall, f1 measures.


In [13]:
# code
from google.colab import drive
drive.mount('/content/gdrive')
%cd '/content/gdrive/MyDrive/ML'

df = pd.read_csv("creditcard.csv")

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
/content/gdrive/MyDrive/ML


In [14]:
X = df.drop('Class', axis=1)
y = df['Class']

X_new = SelectKBest(score_func=f_classif, k=10).fit_transform(X,y)
X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size=0.07, random_state=0, train_size=0.04)
     

# Decision tree
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)

accuracy_dt = accuracy_score(y_test, y_pred_dt)
precision_dt = precision_score(y_test, y_pred_dt, average='macro')
recall_dt = recall_score(y_test, y_pred_dt, average='macro')
f1_dt = f1_score(y_test, y_pred_dt, average='macro')

# kNN
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred_knn = knn.predict(X_test)

accuracy_knn = accuracy_score(y_test, y_pred_knn)
precision_knn = precision_score(y_test, y_pred_knn, average='macro')
recall_knn = recall_score(y_test, y_pred_knn, average='macro')
f1_knn = f1_score(y_test, y_pred_knn, average='macro')

# Logistic Linear 
lr = LogisticRegression(random_state=42,solver='lbfgs', max_iter=10000)
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)

accuracy_lr = accuracy_score(y_test, y_pred_lr)
precision_lr = precision_score(y_test, y_pred_lr, average='macro')
recall_lr = recall_score(y_test, y_pred_lr, average='macro')
f1_lr = f1_score(y_test, y_pred_lr, average='macro')

#SVM 
clf = svm.SVC(kernel='linear') 
clf.fit(X_train, y_train)
y_pred_svm = clf.predict(X_test)

accuracy_svm = accuracy_score(y_test, y_pred_svm)
precision_svm = precision_score(y_test, y_pred_svm, average='macro')
recall_svm = recall_score(y_test, y_pred_svm, average='macro')
f1_svm = f1_score(y_test, y_pred_svm, average='macro')

#Random forest
clf=RandomForestClassifier(n_estimators=100)
clf.fit(X_train,y_train)
y_pred_Rf = clf.predict(X_test)

accuracy_rf = accuracy_score(y_test, y_pred_Rf)
precision_rf = precision_score(y_test, y_pred_Rf, average='macro')
recall_rf = recall_score(y_test, y_pred_Rf, average='macro')
f1_rf = f1_score(y_test, y_pred_Rf, average='macro')

#NaiveBayes 
clf = GaussianNB()
clf.fit(X_train, y_train)
y_pred_Bayes = clf.predict(X_test)

accuracy_bayes = accuracy_score(y_test, y_pred_Bayes)
precision_bayes = precision_score(y_test, y_pred_Bayes, average='macro')
recall_bayes = recall_score(y_test, y_pred_Bayes, average='macro')
f1_bayes = f1_score(y_test, y_pred_Bayes, average='macro')


     
     

data={'accuracy':[accuracy_dt,accuracy_knn,accuracy_lr,accuracy_svm,accuracy_rf,accuracy_bayes],
      'precision':[precision_dt,precision_knn,precision_lr,precision_svm,precision_rf,precision_bayes],
      'recall':[recall_dt,recall_knn,recall_lr,recall_svm,recall_rf,recall_bayes],
      'f1':[f1_dt,f1_knn,f1_lr,f1_svm,f1_rf,f1_bayes]}

row_labels = ['Decision tree', 'kNN','Logistic Linear', 'SVM','Random forest','NaiveBayes']

dframe = pd.DataFrame(data=data,index = row_labels)
dframe

accuracy  precision    recall        f1
Decision tree    0.998796   0.882906  0.787324  0.828270
kNN              0.999147   0.905154  0.874824  0.889397
Logistic Linear  0.999147   0.962586  0.812450  0.872921
SVM              0.999248   0.939118  0.862399  0.897072
Random forest    0.999097   0.932982  0.824899  0.871202
NaiveBayes       0.991824   0.588853  0.921055  0.645130

#Finally,
Save a copy in your Github. Remember renaming the notebook.